### ISSUE TITLE
doesn't compile with the latest stable rust

### ISSUE THREAD

**Issue by zoltan** [jaseemabid/deconz-exporter#1]
getting the following while trying to compile:

   ```
Compiling deconz-exporter v0.1.0 (/root/deconz-exporter)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/lib.rs:1:1
  |
1 | #![feature(box_syntax)]
  | ^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `deconz-exporter` due to previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by jaseemabid** [comment]
Ah! Looks like rust removed box_syntax here https://github.com/rust-lang/rust/pull/108471.  Thanks @zoltan 

Do you mind sending a PR to fix this? The feature is used in just one place, so it might be trivial. https://github.com/jaseemabid/deconz-exporter/blob/main/src/lib.rs#L272-L279
